### ISSUE TITLE
Il Campo 'anno' nella tabella games deve trasformarsi in 'data'

### ISSUE THREAD

**Issue by FilippoBonafini** [FilippoBonafini/laravel-boolsteam#30]

**Comment by danielebd** [comment]
modifica apportata in:
- create_game_table.php (migration)
- GameSeeder.php
- config/games.php
- StoreGameRequest.php
- UpdateGameRequest.php
- DatabaseSeeder.php
- views/admin/games/edit.blade.php
- views/admin/games/show.blade.php
- views/admin/games/create.blade.php
